using Microsoft.CodeAnalysis;

namespace SourceGenerator;

[Generator]
public class SomeTypeGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        // Find the main method
        var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);


        // Build up the source code
        string source = $@"// <auto-generated/>
using System;

    public class MyImplementationOfType : ISomeType
    {{
        public string Name => ""Its Name from MyImplementationOfType"";
    }}

";
        var typeName = "MyImplementationOfType";

        // Add the source code to the compilation
        context.AddSource($"{typeName}.g.cs", source);
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required for this one
    }
}